<?php
/**
 * Mirasvit
 *
 * This source file is subject to the Mirasvit Software License, which is available at https://mirasvit.com/license/.
 * Do not edit or add to this file if you wish to upgrade the to newer versions in the future.
 * If you wish to customize this module for your needs.
 * Please refer to http://www.magentocommerce.com for more information.
 *
 * @category  Mirasvit
 * @package   mirasvit/module-seo
 * @version   2.12.8
 * @copyright Copyright (C) 2026 Mirasvit (https://mirasvit.com/)
 */



namespace Mirasvit\Seo\Service\AutoRedirect;

use Magento\Framework\App\ResourceConnection;
use Mirasvit\Seo\Api\Data\RedirectInterface;
use Mirasvit\Seo\Model\Config;

/**
 * Creates, refreshes, and removes the auto-generated redirect rule(s) for a product.
 *
 * One rule per (product URL, store view), tagged is_autogenerated=1 + source_product_id so it is
 * listable/filterable and never collides with manual rules. A manual rule for the same url_from
 * always wins (AC 6): we skip generating an auto-rule when an active manual rule exists.
 *
 * All writes go through one raw connection in a single transaction per call (delete-then-insert),
 * so the result is deterministic regardless of how many times a product save dispatches the
 * lifecycle event, and never accumulates duplicate or stale-target rows.
 */
class RuleManager
{
    /**
     * @var ResourceConnection
     */
    private $resource;

    /**
     * @var Config
     */
    private $config;

    public function __construct(
        ResourceConnection $resource,
        Config             $config
    ) {
        $this->resource = $resource;
        $this->config   = $config;
    }

    /**
     * Replace a product's auto-redirect rules for a store view with rules to $target.
     *
     * @param string[] $requestPaths product's source request paths (relative, no leading slash)
     */
    public function generate(int $productId, int $storeId, array $requestPaths, string $target): void
    {
        $connection   = $this->resource->getConnection();
        $redirectTbl  = $this->resource->getTableName(RedirectInterface::TABLE_NAME);
        $storeTbl     = $this->resource->getTableName('mst_seo_redirect_store');
        $redirectType = $this->config->getAutoRedirectType($storeId);

        $connection->beginTransaction();
        try {
            foreach ($requestPaths as $requestPath) {
                $urlFrom = '/' . ltrim((string)$requestPath, '/');

                if ($urlFrom === $target || $this->hasManualRule($urlFrom, $storeId)) {
                    // Same as target (would loop), or a manual rule owns this url_from — skip.
                    continue;
                }

                $existingId = $this->findAutoRuleId($urlFrom, $storeId);
                if ($existingId !== null) {
                    // A product save dispatches this several times (per store view / reindex pass);
                    // a pass running while the category link table is mid-rewrite resolves the bare
                    // homepage fallback, a later pass the real category. Keep the more specific
                    // target: a real destination replaces the homepage fallback, never the reverse.
                    if ($target !== '/') {
                        $connection->update(
                            $redirectTbl,
                            ['url_to' => $target, 'redirect_type' => $redirectType],
                            ['redirect_id = ?' => $existingId, 'url_to = ?' => '/']
                        );
                    }

                    continue;
                }

                $connection->insert($redirectTbl, [
                    'url_from'                    => $urlFrom,
                    'url_to'                      => $target,
                    'is_redirect_only_error_page' => 0,
                    'comments'                    => (string)__('Auto-generated for removed product #%1', $productId),
                    'is_active'                   => 1,
                    'redirect_type'               => $redirectType,
                    'is_autogenerated'            => 1,
                    'source_product_id'           => $productId,
                ]);
                $connection->insert($storeTbl, [
                    'redirect_id' => (int)$connection->fetchOne('SELECT LAST_INSERT_ID()'),
                    'store_id'    => $storeId,
                ]);
            }
            $this->dedupe($productId);
            $connection->commit();
        } catch (\Exception $e) {
            $connection->rollBack();
            throw $e;
        }
    }

    /**
     * Collapse duplicate auto-rules for a product to one row per url_from, preferring a real
     * destination over the homepage fallback.
     *
     * A product save can dispatch the lifecycle event several times across nested save/reindex
     * transactions whose writes aren't visible to each other mid-flight, so the per-pass guards
     * cannot always see a sibling pass's freshly-inserted row. This commits a deterministic final
     * state once the writes are flushed: keep the row with a non-"/" url_to where one exists, then
     * the lowest redirect_id; delete the rest.
     */
    private function dedupe(int $productId): void
    {
        $connection  = $this->resource->getConnection();
        $redirectTbl = $this->resource->getTableName(RedirectInterface::TABLE_NAME);
        $storeTbl    = $this->resource->getTableName('mst_seo_redirect_store');

        // Each rule is unique per (url_from, store) — a product on several store views legitimately
        // has one rule per store, so the dedup key must include the store id, not just url_from.
        $rows = $connection->fetchAll(
            $connection->select()
                ->from(['r' => $redirectTbl], ['redirect_id', 'url_from', 'url_to'])
                ->joinLeft(['s' => $storeTbl], 'r.redirect_id = s.redirect_id', ['store_id'])
                ->where('r.is_autogenerated = ?', 1)
                ->where('r.source_product_id = ?', $productId)
                ->order('r.redirect_id ASC')
        );

        $keep = [];
        foreach ($rows as $row) {
            $key     = $row['store_id'] . '|' . $row['url_from'];
            $current = $keep[$key] ?? null;
            // Prefer a non-homepage target; otherwise keep the first seen (lowest id).
            if ($current === null || ($current['url_to'] === '/' && $row['url_to'] !== '/')) {
                $keep[$key] = $row;
            }
        }

        $keepIds = array_unique(array_map(static function ($r) {
            return (int)$r['redirect_id'];
        }, $keep));

        $condition = ['is_autogenerated = ?' => 1, 'source_product_id = ?' => $productId];
        if ($keepIds) {
            $condition['redirect_id NOT IN (?)'] = array_values($keepIds);
        }
        $connection->delete($redirectTbl, $condition);
    }

    /**
     * Remove all auto-generated rules for a product (across every store view).
     * Store linkage rows cascade via the FK on mst_seo_redirect_store.
     */
    public function removeForProduct(int $productId): void
    {
        $connection = $this->resource->getConnection();
        $connection->delete($this->resource->getTableName(RedirectInterface::TABLE_NAME), [
            'is_autogenerated = ?'  => 1,
            'source_product_id = ?' => $productId,
        ]);
    }

    private function hasManualRule(string $urlFrom, int $storeId): bool
    {
        return $this->findRuleId($urlFrom, $storeId, false) !== null;
    }

    private function findAutoRuleId(string $urlFrom, int $storeId): ?int
    {
        return $this->findRuleId($urlFrom, $storeId, true);
    }

    private function findRuleId(string $urlFrom, int $storeId, bool $autogenerated): ?int
    {
        $connection = $this->resource->getConnection();

        $select = $connection->select()
            ->from(['r' => $this->resource->getTableName(RedirectInterface::TABLE_NAME)], ['r.redirect_id'])
            ->joinLeft(
                ['s' => $this->resource->getTableName('mst_seo_redirect_store')],
                'r.redirect_id = s.redirect_id',
                []
            )
            ->where('r.url_from = ?', $urlFrom)
            ->where('r.is_autogenerated = ?', $autogenerated ? 1 : 0)
            ->where('s.store_id IN (?)', [0, $storeId])
            ->limit(1);

        $id = (int)$connection->fetchOne($select);

        return $id > 0 ? $id : null;
    }
}
