<?php

use Mirasvit\SeoContent\Block\Adminhtml\Rewrite\Import\Edit;

/** @var Edit $block */
?>

<div class="import-export-rewrite">
    <div class="import-rewrite">
        <form id="import_form"
              action="<?php /* @escapeNotVerified */ echo $block->getUrl('seo_content/rewrite_import/save') ?>"
              method="post"
              enctype="multipart/form-data">
            <?php echo $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset admin__fieldset">
                <legend class="hidden"><?= $block->escapeHtml(__('SEO Rewrite Import')) ?></legend>
                <div class="admin__field required">
                    <label for="import_file" class="admin__field-label">
                        <span><?php /* @escapeNotVerified */ echo __('Import rewrites (.csv)') ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="file" id="import_file" name="import_file" class="input-file required-entry"/>
                        <?php echo $block->getButtonHtml(__('Import rewrites'), '', 'import-submit') ?>
                        <label id="file-error" class="mage-error hidden">
                            <?= $block->escapeHtml(__('This is a required field.')) ?>
                        </label>
                        <div class="note" id="file-note">
                            <a href="<?php  /* @escapeNotVerified */  echo $block->getDownloadUrl() ?>"><?= $block->escapeHtml(__('Example of CSV file')) ?></a>
                        </div>
                    </div>
                    <div class="page-actions">
                        <div class="page-actions-buttons">
                            <?= $block->getButtonHtml(__('Back'), "setLocation('" . $block->escapeUrl($block->getBackUrl()) . "')", 'back', 'back') ?>
                        </div>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <div class="export-rewrite">
        <form id="export_form"
              action="<?php /* @escapeNotVerified */ echo $block->getUrl('seo_content/rewrite_import/export') ?>"
              method="post"
              enctype="multipart/form-data">
            <?php echo $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset admin__fieldset">
                <legend class="hidden"><?= $block->escapeHtml(__('SEO Rewrite Export')) ?></legend>
                <div class="admin__field">
                    <span class="admin__field-label">
                        <span><?php /* @escapeNotVerified */ echo __('Export rewrites (.csv)') ?></span>
                    </span>
                    <div class="admin__field-control">
                        <?php echo $block->getButtonHtml(__('Export rewrites'), 'export_form.submit()') ?>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>

<script>
    require(['jquery', "mage/mage", "loadingPopup"], function (jQuery) {
        jQuery('#import_form').mage('form').mage('validation');
        (function ($) {
            $('.import-submit').click(function () {
                if ($(':input[name="import_file"]').val()) {
                    $(this.form).submit();
                } else {
                    $('#file-error').removeClass('hidden');
                }
            });
        })(jQuery);
    });
</script>
