
<?php

use Mageplaza\ExtraFee\Helper\Data;

/** @var $block \Mageplaza\ExtraFee\Block\Cart\ExtraFee */
$helper = $this->helper('Mageplaza\ExtraFee\Helper\Data');

?>
<script>
    function initExtraFee() {
        return {
            displayMode: window.checkoutConfig.reviewShippingDisplayMode,
            getTitle(segment) {
                let data =JSON.parse(JSON.stringify(segment));
                var labelText = data.extension_attributes.rule_label;
                var titleText = (data.title && !data.code.includes('auto')) ? ' - ' + data.title : '';
                var fullText = labelText + titleText;

                return fullText;
            },

            getValue: function (value) {
                return hyva.formatPrice(value);
            },
            isBothPricesDisplayed: function () {
                return 'both' === this.displayMode
            },
            isIncludingDisplayed: function () {
                return 'including' === this.displayMode;
            },
            isExcludingDisplayed: function () {
                return 'excluding' === this.displayMode;
            }
        }
    }
</script>
<template x-if="segment.code.indexOf('mp_extra_fee_rule') !== -1">
    <div x-data="initExtraFee()">
        <template x-if="isBothPricesDisplayed()">
            <div class="flex pb-2 my-2 border-b text-md lg:text-sm md:grid md:grid-cols-2 md:w-full border-container"  >
                <div class="w-7/12 text-left md:w-auto"
                 x-html="getTitle(segment) + '(Excl. Tax)'"
                ></div>
                <div class="w-5/12 text-right md:w-auto"
                 x-text="getValue(segment.value)"
                ></div>
            </div>

            <div class="flex pb-2 my-2 border-b text-md lg:text-sm md:grid md:grid-cols-2 md:w-full border-container"  >
                <div class="w-7/12 text-left md:w-auto"
                     x-html="getTitle(segment) + '(Incl. Tax)'"
                ></div>
                <div class="w-5/12 text-right md:w-auto"
                     x-text="getValue(segment.extension_attributes.value_incl_tax)"
                ></div>
            </div>
        </template>

        <template x-if="isIncludingDisplayed()">
            <div class="flex pb-2 my-2 border-b text-md lg:text-sm md:grid md:grid-cols-2 md:w-full border-container"  >
                <div class="w-7/12 text-left md:w-auto"
                     x-html="getTitle(segment) + '(Excl. Tax)'"
                ></div>
                <div class="w-5/12 text-right md:w-auto"
                     x-text="getValue(segment.extension_attributes.value_incl_tax)"
                ></div>
            </div>
        </template>

        <template x-if="isExcludingDisplayed()">
            <div class="flex pb-2 my-2 border-b text-md lg:text-sm md:grid md:grid-cols-2 md:w-full border-container"  >
                <div class="w-7/12 text-left md:w-auto"
                     x-html="getTitle(segment)"
                ></div>
                <div class="w-5/12 text-right md:w-auto"
                     x-text="getValue(segment.value)"
                ></div>
            </div>
        </template>
    </div>

</template>
