<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Title;

/** @var Escaper $escaper */
/** @var Title $block */

$headingTag = $block->getData('heading_tag') ?: 'h1';
$cssClasses = $block->getCssClasses() ?? $block->getCssClass() ?? 'text-3xl font-bold mb-6';
$wrapperCssClasses = $block->getWrapperCssClasses()
    ?? $block->getData('maybe_purged_tailwind_section_classes')
    ?? 'flex flex-col md:flex-row flex-wrap md:border-b md:border-[#e5e7eb] md:pb-6';
$baseAttribute = $block->getAddBaseAttribute();

$titleHtml = trim((string)$block->getPageHeading()) ?: '';
?>
<?php if ($titleHtml): ?>
    <div class="<?= $escaper->escapeHtmlAttr($wrapperCssClasses) ?>">
        <<?= $escaper->escapeHtmlAttr($headingTag) ?>
            class="page-title container <?= $escaper->escapeHtmlAttr($cssClasses); ?>"
            <?= $escaper->escapeHtmlAttr($baseAttribute, false); ?>
            data-ui-id="page-title-wrapper"
        >
            <?= $escaper->escapeHtml($titleHtml) ?>
        </<?= $escaper->escapeHtmlAttr($headingTag) ?>>
        <?= $block->getChildHtml() ?>
    </div>
<?php endif; ?>
