<?php
$element    = $this->getElement();
$coreHelper = $this->helper('\Magezon\Core\Helper\Data');
$boxStyle   = $element->getData('message_box_style');
$boxShape   = $element->getData('message_box_shape');
$icon       = $element->getData('icon');
?>
<div class="mgz-message-box mgz-message-box-<?= $block->escapeHtmlAttr($boxStyle) ?> mgz-message-box-<?= $block->escapeHtmlAttr($boxShape) ?>">
	<div class="mgz-message-box-icon"><i class="<?= $block->escapeHtmlAttr($icon) ?>"></i></div>
	<div class="mgz-message-box-content"><?= /* @noEscape */ $coreHelper->filter($element->getContent()) ?></div>
</div>