<?php
use Magento\Framework\App\Action\Action;

$coreHelper           = $this->helper('\Magezon\Core\Helper\Data');
$compareHelper        = $this->helper('Magento\Catalog\Helper\Product\Compare');
$element              = $this->getElement();
$title                = $coreHelper->filter($element->getData('title'));
$titleAlign           = $element->getData('title_align');
$titleTag             = $element->getData('title_tag') ? $element->getData('title_tag') : 'h2';
$description          = $coreHelper->filter($element->getData('description'));
$showLine             = $element->getData('show_line');
$linePosition         = $element->getData('line_position');
$items                = $this->getItems();
$imageId              = 'category_page_list';
$templateType         = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$showImage            = $element->getData('product_image');
$showName             = $element->getData('product_name');
$showPrice            = $element->getData('product_price');
$showShortDescription = $element->getData('product_shortdescription');
$showWishlist         = $element->getData('product_wishlist');
$showCompare          = $element->getData('product_compare');
$showCart             = $element->getData('product_addtocart');
$showReview           = $element->getData('product_review');
$swatches             = $element->getData('product_swatches');
$htmlId               = $element->getHtmlId();
?>
<div class="mgz-block">
	<?php if ($title || $description) { ?>
	<div class="mgz-block-heading mgz-block-heading-align-<?= $block->escapeHtmlAttr($titleAlign) ?><?= $showLine ? ' mgz-block-heading-line' : '' ?> mgz-block-heading-line-position-<?= $block->escapeHtmlAttr($linePosition) ?>">
		<?php if ($title) { ?>
			<<?= $block->escapeHtmlAttr($titleTag) ?> class="title"><?= /* @noEscape */ $title ?></<?= $block->escapeHtmlAttr($titleTag) ?>>
		<?php } ?>
		<?php if ($description) { ?>
			<div class="info"><?= /* @noEscape */ $description ?></div>
		<?php } ?>
	</div>
	<?php } ?>
	<div class="mgz-block-content">
		<div class="mgz-product-list products-list">
			<?php foreach ($items as $_product) { ?>
				<div class="item product product-item">
					<div class="product-item-info">
						<?php if ($showImage) { ?>
						<?php $productImage = $block->getImage($_product, $imageId); ?>
	                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo" tabindex="-1">
	                        <?= $productImage->toHtml() ?>
	                    </a>
						<?php } ?>
						<div class="product details product-item-details">
							<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>

							<?php if ($showName) { ?>
								<strong class="product-item-name">
									<a title="<?= $block->escapeHtml($_product->getName()) ?>"
										href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>"
										class="product-item-link">
										<?= $block->escapeHtml($_product->getName()) ?>
									</a>
								</strong>
							<?php } ?>

							<?= ($templateType && $showReview) ? $block->getReviewsSummaryHtml($_product, $templateType) : '' ?>

							<?= $showPrice ? /* @noEscape */ $block->getProductPrice($_product) : '' ?>

							<?= $swatches ? $this->getSwatchesHtml($_product) : '' ?>

							<?php if ($showWishlist || $showCompare || $showCart) { ?>
								<div class="product-item-actions">
									<?php if ($showCart) { ?>
										<div class="actions-primary">
											<?php if ($_product->isSaleable()) { ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form" action="<?= $block->escapeUrl($postParams['action']); ?>" method="post">
													<input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']); ?>">
													<input type="hidden" name="<?= $block->escapeHtmlAttr(Action::PARAM_NAME_URL_ENCODED); ?>" value="<?= $block->escapeHtmlAttr($postParams['data'][Action::PARAM_NAME_URL_ENCODED]); ?>">
													<?php if ($formKey = $block->getProductFormKey()) { ?>
														<input name="form_key" type="hidden" value="<?= $block->escapeHtmlAttr($formKey) ?>" />
														<?php } else { ?>
														<?= $block->getBlockHtml('formkey')?>
														<?php } ?>
														<button type="submit"
														title="<?= $block->escapeHtml(__('Add to Cart')); ?>"
														class="action tocart primary">
														<span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
													</button>
												</form>
											<?php } else { ?>
												<?php if ($_product->getIsSalable()) { ?>
													<div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
												<?php } else { ?>
													<div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
												<?php } ?>
											<?php } ?>
										</div>
									<?php } ?>
									<?php if ($showWishlist || $showCompare) { ?>
										<div class="actions-secondary" data-role="add-to-links">
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist) { ?>
												<a href="#"
													data-post='<?= $block->escapeHtmlAttr($block->getAddToWishlistParams($_product)) ?>'
													class="action towishlist" data-action="add-to-wishlist"
													title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
													<span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
												</a>
											<?php } ?>
											<?php if ($block->getAddToCompareUrl() && $showCompare) { ?>
												<a href="#" class="action tocompare"
													data-post='<?= $block->escapeHtmlAttr($compareHelper->getPostDataParams($_product)) ?>'
													title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
													<span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
												</a>
											<?php } ?>
										</div>
									<?php } ?>
								</div>
							<?php } ?>

							<?php if ($showShortDescription) { ?>
								<div class="product description product-item-description">
									<?= /* @noEscape */ $coreHelper->filter($_product->getShortDescription()) ?>
									<a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" title="<?= $block->escapeHtmlAttr($_productNameStripped) ?>"
                                       class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
								</div>
							<?php } ?>
						</div>
					</div>
				</div>
			<?php } ?>
		</div>
	</div>
	<script type="text/x-magento-init">
	{
	    ".<?= $block->escapeJs($htmlId) ?> [data-role=tocart-form]": {
	        "catalogAddToCart": {
	        }
	    }
	}
	</script>
</div>