<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

/*
 * Secomm override (BUG-SDZPCD / ext ticket SLP-109):
 * Fee form + AJAX script extracted from Mageplaza_ExtraFee::hyva/product/view/addtocart.phtml
 * (original copyright Mageplaza) into this dedicated block so it renders full-width
 * below the product price instead of inside the qty/add-to-cart column.
 * Re-sync with the module's addtocart.phtml fee section on module upgrades.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Mageplaza\ExtraFee\Block\Product\View;

/** @var View $block */
/** @var Escaper $escaper */
?>
<?php if ($block->isDisplayExtraFee()) : ?>
    <?php $ajaxUrl = $block->getUrl('mpextrafee/product/extrafee'); ?>
    <div class="mp-extrafee-form mt-3 mb-3 w-full">
        <div class="mp-extrafee-title"><?= $block->escapeHtml(__($block->getExtraFeeTitle())) ?></div>
        <div id="mp-extrafee-content" class="mt-3 mb-3"></div>
        <button class="action primary btn btn-primary" type="button" id="calculated-extra-fee">
            <?= $block->escapeHtml(__('Calculate Extra Fee')) ?>
        </button>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var initUrl = "<?= $block->escapeUrl($ajaxUrl) ?>";
            getContent(initUrl);
            document.getElementById('calculated-extra-fee').addEventListener('click', function () {
                getContent("<?= $block->escapeUrl($ajaxUrl) ?>");
            });
            function getContent(ajaxUrl) {
                fetch(ajaxUrl, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded',
                    },
                    body: new URLSearchParams(new FormData(document.getElementById('product_addtocart_form'))).toString(),
                })
                    .then(response => response.json())
                    .then(data => {
                        document.getElementById('mp-extrafee-content').innerHTML = data.content;
                    })
                    .catch(error => console.error('Error fetching data:', error));
            }
        });
    </script>
    <style type="text/css">
        .mp-extrafee-form {
            margin-bottom: 20px;
        }

        .mp-extrafee-title {
            font-weight: 700;
            font-size: 1.2rem;
        }

        #mp-extrafee-content {
            margin-top: 10px;
        }

        #mp-extrafee-content .mp-extrafee-name {
            font-weight: 700;
            font-size: 1.1rem;
        }

        #mp-extrafee-content .mp-extrafee-desc {
            font-style: italic;
            margin-top: 5px;
            margin-bottom: 5px;
        }

        #mp-extrafee-content ul {
            list-style-type: disc;
            padding: 0 0 0 40px;
        }

        .bundle-options-container #calculated-extra-fee {
            padding: 7px 15px;
            font-size: 14px;
        }
    </style>
<?php endif; ?>
