<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<?php $_product = $block->getProduct();
?>
<?php
$ajaxUrl = $block->getUrl('mpextrafee/product/extrafee');
?>
<div>
<?php if ($block->isDisplayExtraFee() && $block->getExtraFeePosition() == 1) : ?>
    <div class="mp-extrafee-form mt-3 mb-3">
        <div class="mp-extrafee-title"><?= $block->escapeHtml(__($block->getExtraFeeTitle())) ?></div>
        <div id="mp-extrafee-content" class="mt-3 mb-3"></div>
        <button class="action primary btn btn-primary" type="button" id="calculated-extra-fee">
            <?= $block->escapeHtml(__('Calculate Extra Fee'))?>
        </button>
    </div>
<?php endif; ?>
<button type="submit"
        form="product_addtocart_form"
        title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
        class="btn btn-primary"
        id="product-addtocart-button"
        data-addto="cart"
>
    <?= $heroicons->shoppingCartHtml('border-current'); ?>
    <span class="hidden sm:block md:hidden lg:block"><?= $block->getData('is_cart_configure') ?
            $escaper->escapeHtml(__('Update item')) :
            $escaper->escapeHtml(__('Add to Cart')) ?>
    </span>
</button>
<?php if ($block->isDisplayExtraFee() && $block->getExtraFeePosition() == 2) : ?>
    <div class="mp-extrafee-form mt-3 mb-3">
        <div class="mp-extrafee-title"><?= $block->escapeHtml(__($block->getExtraFeeTitle())) ?></div>
        <div id="mp-extrafee-content" class="mt-3 mb-3"></div>
        <button class="action primary btn btn-primary" type="button" id="calculated-extra-fee">
            <?= $block->escapeHtml(__('Calculate Extra Fee'))?>
        </button>
    </div>
<?php endif; ?>
<?= $block->getChildHtml('', true) ?>
</div>
<style type="text/css">
    .mp-extrafee-form {
        margin-bottom: 20px;
    }

    .mp-extrafee-title {
        font-weight: 700;
        font-size: 1.2rem;
    }

    #mp-extrafee-content {
        margin-top: 10px;
    }

    #mp-extrafee-content .mp-extrafee-name {
        font-weight: 700;
        font-size: 1.1rem;
    }

    #mp-extrafee-content .mp-extrafee-desc {
        font-style: italic;
        margin-top: 5px;
        margin-bottom: 5px;
    }
    #mp-extrafee-content ul {
        list-style-type:disc;
        padding: 0 0 0 40px;
    }
    .bundle-options-container #calculated-extra-fee {
        padding: 7px 15px;
        font-size: 14px;
    }
</style>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var initUrl = "<?= $block->escapeUrl($ajaxUrl) ?>";
        getContent(initUrl);
        document.getElementById('calculated-extra-fee').addEventListener('click', function() {
            var ajaxUrl = "<?= $block->escapeUrl($ajaxUrl) ?>";
            getContent(ajaxUrl);
        });
        function getContent(ajaxUrl) {
            fetch(ajaxUrl, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                },
                body: new URLSearchParams(new FormData(document.getElementById('product_addtocart_form'))).toString(),
            })
            .then(response => response.json())
            .then(data => {
                let contentExtraFee =  document.getElementById('mp-extrafee-content');
                contentExtraFee.innerHTML = data.content;
            })
            .catch(error => {
                console.error('Error fetching data:', error);
            });
        }
    });
</script>
