<?php
$dataHelper    = $this->helper('\Magezon\Builder\Helper\Data');
$element       = $block->getElement();
$id            = $element->getId();
$googleApi     = $dataHelper->getGoogleMapApi();
$zoom          = $element->getMapZoom();
$type          = $element->getMapType();
$ui            = $element->getMapUi();
$scrollwheel   = $element->getMapScrollwheel();
$draggable     = $element->getMapDraggable();
$infoboxOpened = $element->getData('infobox_opened');
$items         = $this->getItems();
$mapId         = $id . '-map';
$centerItem    = $this->getCenterItem();
?>
<?php if ($googleApi && $centerItem) { ?>
	<div id="<?= $escaper->escapeHtmlAttr($mapId) ?>"></div>
	<script>
		require([
			'jquery',
			'https://maps.google.com/maps/api/js?key=<?= $escaper->escapeUrl($googleApi) ?>&libraries=places'
		], function() {
			var initGoogleMap<?= $escaper->escapeJs($id) ?> = function () {
				var config = {
					center: {
						lat: <?= $escaper->escapeJs($centerItem['lat']) ?>,
						lng: <?= $escaper->escapeJs($centerItem['lng']) ?>
					},
					zoom: <?= $escaper->escapeJs($zoom) ?>,
					mapTypeId: '<?= $escaper->escapeJs($type) ?>',
					disableDefaultUI: <?= $ui ? 'true' : 'false' ?>,
					scrollwheel: <?= $scrollwheel ? 'true' : 'false' ?>,
					draggable: <?= $draggable ? 'true' : 'false' ?>
				};
				var map = new google.maps.Map(document.getElementById('<?= $escaper->escapeHtmlAttr($mapId) ?>'), config);
				<?php if ($items) { ?>
					<?php foreach ($items as $option) { ?>
						<?php if ($option) { ?>
							var myLatLng = new google.maps.LatLng(<?= $escaper->escapeJs($option['lat']) ?>, <?= $escaper->escapeJs($option['lng']) ?>);
							addMarker(myLatLng, map, <?= /* @noEscape */ json_encode($option, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP) ?>);
						<?php } ?>
					<?php } ?>
				<?php } ?>
				function addMarker(location, map, option) {
					var marker = new google.maps.Marker({
						position: location,
						map: map,
						icon: option['image']
					});
					if (option['info']) {
						var infowindow = new google.maps.InfoWindow({
							content: option['info']
						});
						marker.addListener('click', function() {
							infowindow.open(map, marker);
						});
						<?php if ($infoboxOpened) { ?>
							infowindow.open(map, marker);
						<?php } ?>
					}
				}
			}
			setTimeout(function() {
				initGoogleMap<?= /* @noEscape */ $id ?>();
			}, 1000);
		});
	</script>
<?php } ?>