<?php
/**
 * @var $block \Magezon\Builder\Block\Element
 */
?>
<?php
$element      = $this->getElement();
$title        = $element->getData('title');
$titleTag     = $element->getData('title_tag') ? $element->getData('title_tag') : 'h4';
$titleAlign   = $element->getData('title_align') ? $element->getData('title_align') : 'center';
$addIcon      = $element->getData('add_icon');
$iconPosition = $element->getData('icon_position');
$icon         = $element->getData('icon');
$allowedTags = ['h1','h2','h3','h4','h5','h6'];
if (!in_array($titleTag, $allowedTags, true)) {
    $titleTag = 'h4';
}
?>
<div class="mgz-element-separator-wrapper mgz-text-<?= $escaper->escapeHtmlAttr($titleAlign) ?>">
	<?php if ($title || ($addIcon && $icon)) { ?>
	<<?= $titleTag ?> class="title">
		<?php if ($addIcon && $icon && $iconPosition == 'left') { ?>
			<i class="mgz-icon-element <?= $escaper->escapeHtmlAttr($icon) ?>"></i>
		<?php } ?>
		<?php if ($title) { ?>
			<span><?= $escaper->escapeHtml($title) ?></span>
		<?php } ?>
		<?php if ($addIcon && $icon && $iconPosition == 'right') { ?>
			<i class="mgz-icon-element <?= $escaper->escapeHtmlAttr($icon) ?>"></i>
		<?php } ?>
	</<?= $titleTag ?>>
	<?php } ?>
	<div class="mgz-element-separator-line"></div>
</div>