<?php
$coreHelper   = $this->helper('\Magezon\Core\Helper\Data');
$element      = $this->getElement();
$id           = $element->getHtmlId();
$items        = $this->toObjectArray($element->getItems());
$linkTarget   = $element->getData('link_target');
$followButton = $element->getData('follow_button');
?>
<?php if ($items) { ?>
	<ul class="mgz-socialicons">
	<?php foreach ($items as $i => $item) { ?>
		<?php
		$label = $this->getSocialLabel($item['icon']);
		$link  = $coreHelper->filter($item['link'] ? $item['link'] : '#');
		?>
		<li>
			<a href="<?= $escaper->escapeUrl($link) ?>" target="<?= $escaper->escapeHtmlAttr($linkTarget) ?>" rel="noreferrer" title="<?= $escaper->escapeHtmlAttr(__('Follow on %1', $label)) ?>">
				<i id="<?= $escaper->escapeHtmlAttr($id) ?>-mgz-socialicons-item<?= $escaper->escapeHtmlAttr($i) ?>" class="<?= $escaper->escapeHtmlAttr($item['icon']) ?>"></i>
			</a>
			<?php if ($followButton) { ?>
				<a href="<?= $escaper->escapeUrl($link) ?>" class="mgz-socialicons-follow-button" title="<?= $block->escapeHtml($label) ?>"><?= $escaper->escapeHtml(__('Follow')) ?></a>
			<?php } ?>
		</li>	
	<?php } ?>
	</ul>
<?php } ?>