<?php
/*
 * @author Secomm Team
 * @copyright Copyright (c) 2026. Secomm All rights reserved (https://www.secomm.vn)
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Secomm\PromotionMaxDiscount\Plugin\Adminhtml\Rule\Metadata;

use Magento\SalesRule\Model\Rule\Metadata\ValueProvider;

/**
 * Injects the Maximum Discount Amount field into the cart price rule Actions
 * tab (TASK-67GGPR / SPEC-FEAT-JKZM68 §6 / DEC-FEATJKZM68-001 §7).
 *
 * The sales_rule_form.xml core file is deliberately NOT overridden (AC-5 —
 * copying 700 upgrade-brittle lines); instead this after-plugin adds exactly
 * one key to the ValueProvider metadata. Positioning: the Actions fieldset
 * fields carry no explicit sortOrder in the core XML, so with equal sort
 * orders the children render in array order — the field is spliced in right
 * after discount_amount (AC-1) without touching any other key's config.
 *
 * Visibility/enabled gating by simple_action lives in the JS component
 * (max-discount-field); the runtime collector guard is independent of this UI
 * (TASK-5H8WKE checks simple_action at calculation time).
 */
final class ViewProviderPlugin
{
    public const FIELD_NAME = 'maximum_discount_amount';

    /**
     * @param ValueProvider $subject
     * @param array $result
     * @return array
     */
    public function afterGetMetadataValues(ValueProvider $subject, array $result): array
    {
        if (!isset($result['actions']['children']) || !is_array($result['actions']['children'])) {
            // No Actions section to splice into — pass through unchanged.
            return $result;
        }
        $children = $result['actions']['children'];
        if (array_key_exists(self::FIELD_NAME, $children)) {
            // A future core version ships the field natively — never override core.
            return $result;
        }

        $result['actions']['children'] = $this->spliceAfterDiscountAmount($children, $this->fieldConfig());
        return $result;
    }

    /**
     * @return array<string, mixed>
     */
    private function fieldConfig(): array
    {
        return [
            'arguments' => [
                'data' => [
                    'config' => [
                        'source' => 'sales_rule',
                        // required for meta-created components: UiComponentFactory::
                        // mergeMetadataItem() creates a component for an unknown meta
                        // child only when componentType is present — otherwise the
                        // whole form throws LocalizedException
                        'componentType' => 'field',
                        'component' => 'Secomm_PromotionMaxDiscount/js/form/element/max-discount-field',
                        'formElement' => 'input',
                        'dataType' => 'text',
                        'label' => __('Maximum Discount Amount'),
                        'notice' => __(
                            'Limits the total product discount generated by this rule. '
                            . 'Leave empty or set to 0 for no limit.'
                        ),
                        'dataScope' => self::FIELD_NAME,
                        'visible' => false, // JS toggles by simple_action; hidden until the import fires
                        'validation' => [
                            'validate-number' => true,
                            'validate-zero-or-greater' => true,
                        ],
                    ],
                ],
            ],
        ];
    }

    /**
     * Rebuild the children with our field inserted right after discount_amount,
     * keys and configs of every core field untouched.
     *
     * @param array<string, mixed> $children
     * @param array<string, mixed> $field
     * @return array<string, mixed>
     */
    private function spliceAfterDiscountAmount(array $children, array $field): array
    {
        if (!array_key_exists('discount_amount', $children)) {
            $children[self::FIELD_NAME] = $field;
            return $children;
        }

        $rebuilt = [];
        foreach ($children as $name => $config) {
            $rebuilt[$name] = $config;
            if ($name === 'discount_amount') {
                $rebuilt[self::FIELD_NAME] = $field;
            }
        }
        return $rebuilt;
    }
}
