<?php
/**
 * Mirasvit
 *
 * This source file is subject to the Mirasvit Software License, which is available at https://mirasvit.com/license/.
 * Do not edit or add to this file if you wish to upgrade the to newer versions in the future.
 * If you wish to customize this module for your needs.
 * Please refer to http://www.magentocommerce.com for more information.
 *
 * @category  Mirasvit
 * @package   mirasvit/module-seo
 * @version   2.12.8
 * @copyright Copyright (C) 2026 Mirasvit (https://mirasvit.com/)
 */


declare(strict_types=1);

namespace Mirasvit\Seo\Api\Data;

/**
 * @api
 */
interface RedirectInterface
{
    const TABLE_NAME = 'mst_seo_redirect';

    const ID                        = 'redirect_id';
    const URL_FROM                  = 'url_from';
    const URL_TO                    = 'url_to';
    const IS_REDIRECT_ONLY_ERROR_PAGE = 'is_redirect_only_error_page';
    const COMMENTS                  = 'comments';
    const IS_ACTIVE                 = 'is_active';
    const REDIRECT_TYPE             = 'redirect_type';
    const IS_AUTOGENERATED          = 'is_autogenerated';
    const SOURCE_PRODUCT_ID         = 'source_product_id';
    const STORE_IDS                 = 'store_ids';

    /**
     * @return int|null
     */
    public function getId();

    /**
     * @return string|null
     */
    public function getUrlFrom(): ?string;

    /**
     * @param string|null $value
     * @return $this
     */
    public function setUrlFrom(?string $value): self;

    /**
     * @return string|null
     */
    public function getUrlTo(): ?string;

    /**
     * @param string|null $value
     * @return $this
     */
    public function setUrlTo(?string $value): self;

    /**
     * @return int|null
     */
    public function getIsRedirectOnlyErrorPage(): ?int;

    /**
     * @param int|null $value
     * @return $this
     */
    public function setIsRedirectOnlyErrorPage(?int $value): self;

    /**
     * @return string|null
     */
    public function getComments(): ?string;

    /**
     * @param string|null $value
     * @return $this
     */
    public function setComments(?string $value): self;

    /**
     * @return int|null
     */
    public function getIsActive(): ?int;

    /**
     * @param int|null $value
     * @return $this
     */
    public function setIsActive(?int $value): self;

    /**
     * @return int|null
     */
    public function getRedirectType(): ?int;

    /**
     * @param int|null $value
     * @return $this
     */
    public function setRedirectType(?int $value): self;

    /**
     * @return int|null
     */
    public function getIsAutogenerated(): ?int;

    /**
     * @param int|null $value
     * @return $this
     */
    public function setIsAutogenerated(?int $value): self;

    /**
     * @return int|null
     */
    public function getSourceProductId(): ?int;

    /**
     * @param int|null $value
     * @return $this
     */
    public function setSourceProductId(?int $value): self;

    /**
     * @return int[]
     */
    public function getStoreIds(): array;

    /**
     * @param int[] $value
     * @return $this
     */
    public function setStoreIds(array $value): self;
}
