<?php
/**
 * Mirasvit
 *
 * This source file is subject to the Mirasvit Software License, which is available at https://mirasvit.com/license/.
 * Do not edit or add to this file if you wish to upgrade the to newer versions in the future.
 * If you wish to customize this module for your needs.
 * Please refer to http://www.magentocommerce.com for more information.
 *
 * @category  Mirasvit
 * @package   mirasvit/module-seo
 * @version   2.12.8
 * @copyright Copyright (C) 2026 Mirasvit (https://mirasvit.com/)
 */



namespace Mirasvit\SeoSitemap\Preference\ResourceModel;

use Magento\CatalogUrlRewrite\Model\ProductUrlRewriteGenerator;
use Magento\Framework\App\ObjectManager;
use Magento\Store\Api\Data\StoreInterface;
use Magento\Sitemap\Model\Source\Product\Image\IncludeImage;

class Product extends \Magento\Sitemap\Model\ResourceModel\Catalog\Product
{
    private const MEDIA_TYPE_VIDEO = 'external-video';

    /**
     * @var \Magento\Catalog\Helper\Image|null
     */
    private $catalogImageHelper;

    /**
     * @var null|bool
     */
    private $isImageFriendlyUrlEnabled = null;

    /**
     * @var string
     */
    private $imageUrlTemplate = null;

    /**
     * @var \Magento\Catalog\Api\ProductRepositoryInterface|null
     */
    private $productRepository;

    /**
     * @var \Mirasvit\Seo\Api\Service\FriendlyImageUrlServiceInterface\Proxy|null
     */
    private $friendlyImageUrlService;

    /**
     * @var \Mirasvit\Seo\Model\Config|null
     */
    private $config;

    /**
     * @var \Mirasvit\SeoSitemap\Model\Config|null
     */
    private $sitemapConfig;

    /**
     * @var \Magento\InventorySalesApi\Api\StockResolverInterface|null
     */
    private $stockResolver;

    /**
     * @var \Magento\InventorySalesApi\Api\GetProductSalableQtyInterface|null
     */
    private $getProductSalableQty;

    /**
     * @var \Magento\Framework\Module\Manager|null
     */
    private $moduleManager;

    /**
     * @var bool
     */
    private $isProductVideoEnabled = false;

    /**
     * @var array
     */
    private $productGalleryCache = [];

    protected function _construct()
    {
        $this->_init('catalog_product_entity', 'entity_id');

        $this->catalogImageHelper = ObjectManager::getInstance()->get(\Magento\Catalog\Helper\Image::class);

        $this->productRepository = ObjectManager::getInstance()->get(\Magento\Catalog\Api\ProductRepositoryInterface::class);

        $this->moduleManager = ObjectManager::getInstance()->get(\Magento\Framework\Module\Manager::class);

        $this->isProductVideoEnabled = $this->moduleManager !== null && $this->moduleManager->isEnabled('Magento_ProductVideo');

        if ($this->moduleManager !== null && $this->moduleManager->isEnabled('Mirasvit_Seo')) {
            $config = ObjectManager::getInstance()->get(\Mirasvit\Seo\Model\Config\ImageConfig::class);

            if ($config !== null) {
                $this->isImageFriendlyUrlEnabled = $config->isFriendlyUrlEnabled();
                $this->imageUrlTemplate          = $config->getUrlTemplate();
            }

            $this->friendlyImageUrlService = ObjectManager::getInstance()
                ->get(\Mirasvit\Seo\Api\Service\FriendlyImageUrlServiceInterface\Proxy::class);

            $this->config = ObjectManager::getInstance()->get(\Mirasvit\Seo\Model\Config::class);
            $this->sitemapConfig = ObjectManager::getInstance()->get(\Mirasvit\SeoSitemap\Model\Config::class);
        }

        if ($this->moduleManager !== null && $this->moduleManager->isEnabled('Magento_InventorySalesApi')) {
            $this->stockResolver = ObjectManager::getInstance()->get(\Magento\InventorySalesApi\Api\StockResolverInterface::class);

            $this->getProductSalableQty = ObjectManager::getInstance()->get(\Magento\InventorySalesApi\Api\GetProductSalableQtyInterface::class);
        }
    }

    /**
     * @param int $storeId
     * @return array|bool
     * @throws \Magento\Framework\Exception\LocalizedException
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     * @throws \Zend_Db_Statement_Exception
     */
    public function getCollection($storeId)
    {
        $products = [];
        $store = $this->_storeManager->getStore($storeId);
        if (!$store) {
            return false;
        }

        $connection = $this->getConnection();

        $joinCondition = 'e.entity_id = url_rewrite.entity_id AND url_rewrite.is_autogenerated = 1 AND url_rewrite.metadata IS NULL';
        if ($this->config && $this->config->isAddLongestCanonicalProductUrl((int)$store->getId())
            && $this->config->isProductLongUrlEnabled((int)$store->getId())
        ) {
            $joinCondition = 'e.entity_id = url_rewrite.entity_id AND url_rewrite.is_autogenerated = 1';
        }

        $this->_select = $connection->select()->from(
            ['e' => $this->getMainTable()],
            [$this->getIdFieldName(), $this->_productResource->getLinkField(), 'updated_at', 'sku']
        )
            ->joinInner(['w' => $this->getTable('catalog_product_website')], 'e.entity_id = w.product_id', [])
            ->joinLeft(
                ['url_rewrite' => $this->getTable('url_rewrite')],
                $joinCondition
                . $connection->quoteInto(' AND url_rewrite.store_id = ?', $store->getId())
                . $connection->quoteInto(' AND url_rewrite.entity_type = ?', ProductUrlRewriteGenerator::ENTITY_TYPE),
                ['url' => 'request_path']
            )
            ->where('w.website_id = ?', $store->getWebsiteId());

        $this->_addFilter($store->getId(), 'visibility', $this->_productVisibility->getVisibleInSiteIds(), 'in');

        if (is_object($this->sitemapConfig)) {
            if (!$this->sitemapConfig->getIsShowNonSalableProducts($storeId)) {
                $this->_addFilter($store->getId(), 'status', $this->_productStatus->getVisibleStatusIds(), 'in');
            }

            $this->addStockFilter($store);
        } else {
            $this->_addFilter($store->getId(), 'status', $this->_productStatus->getVisibleStatusIds(), 'in');
        }

        $imageIncludePolicy = $this->_sitemapData->getProductImageIncludePolicy($store->getId());
        if (IncludeImage::INCLUDE_NONE != $imageIncludePolicy) {
            if ($this->getNumberOfParameters() > 2) {
                $this->_joinAttribute($store->getId(), 'name', 'name');

                if (IncludeImage::INCLUDE_ALL == $imageIncludePolicy) {
                    $this->_joinAttribute($store->getId(), 'thumbnail', 'thumbnail');
                } elseif (IncludeImage::INCLUDE_BASE == $imageIncludePolicy) {
                    $this->_joinAttribute($store->getId(), 'image', 'image');
                }
            } else {
                $this->_joinAttribute($store->getId(), 'name');
                if (strpos($this->_select->__toString(), 'AS `t2_name`') === false) {
                    $this->_select->columns(
                        ['name' => $this->getConnection()->getIfNullSql('t1_name.value')]
                    );
                } else {
                    $this->_select->columns(
                        ['name' => $this->getConnection()->getIfNullSql('t2_name.value', 't1_name.value')]
                    );
                }

                if (IncludeImage::INCLUDE_ALL == $imageIncludePolicy) {
                    $this->_joinAttribute($store->getId(), 'thumbnail');
                    $this->_select->columns(['thumbnail' => $this->getConnection()->getIfNullSql('t2_thumbnail.value', 't1_thumbnail.value'),]);
                } elseif (IncludeImage::INCLUDE_BASE == $imageIncludePolicy) {
                    $this->_joinAttribute($store->getId(), 'image');
                    $this->_select->columns(
                        ['image' => $this->getConnection()->getIfNullSql('t2_image.value', 't1_image.value')]
                    );
                }
            }
        }
        if ($this->config && $this->config->isAddLongestCanonicalProductUrl((int)$store->getId())
            && $this->config->isProductLongUrlEnabled((int)$store->getId())
        ) {
            $this->_select->order('e.entity_id asc');
            $this->_select->order('length(url_rewrite.request_path) desc');
        }

        $query = $connection->query($this->_select);
        while ($row = $query->fetch()) {
            if (!isset($products[$row[$this->getIdFieldName()]]) && $this->validateStock($row['sku'], $store)) {
                $product                     = $this->_prepareProduct($row, $store->getId());
                $products[$product->getId()] = $product;
            }
        }

        return $products;
    }

    /**
     * @return bool|int
     */
    protected function getNumberOfParameters()
    {
        $numberOfParameters                 = false;
        $checkJoinAttributeReflectionMethod = new \ReflectionMethod(
            \Magento\Sitemap\Model\ResourceModel\Catalog\Product::class,
            '_joinAttribute'
        );
        if (is_object($checkJoinAttributeReflectionMethod)) {
            $numberOfParameters = $checkJoinAttributeReflectionMethod->getNumberOfParameters();
        }

        return $numberOfParameters;
    }

    /**
     * Load product images
     *
     * @param \Magento\Catalog\Model\Product $product
     * @param int                           $storeId
     *
     * @return void
     */
    protected function _loadProductImages($product, $storeId)
    {
        $helper             = $this->_sitemapData;
        $imageIncludePolicy = $helper->getProductImageIncludePolicy($storeId);

        $imagesCollection = [];
        if (IncludeImage::INCLUDE_ALL == $imageIncludePolicy) {
            $imagesCollection = $this->_getAllProductImages($product, $storeId);
        } elseif (IncludeImage::INCLUDE_BASE == $imageIncludePolicy &&
            $product->getImage() &&
            $product->getImage() != self::NOT_SELECTED_IMAGE
        ) {
            $imagesCollection = [
                new \Magento\Framework\DataObject(
                    ['url' => $this->getCurrentProductImageUrl($product, $product->getImage(), $storeId)]
                ),
            ];
        }

        if ($imagesCollection) {
            $thumbnail = $product->getThumbnail();
            if ($thumbnail && $product->getThumbnail() != self::NOT_SELECTED_IMAGE) {
                $thumbnail = $this->getCurrentProductImageUrl($product, $thumbnail, $storeId);
            } else {
                $thumbnail = $this->friendlyImageUrlService !== null
                    ? $this->friendlyImageUrlService->getFriendlyImageName($product, $imagesCollection[0]->getUrl())
                    : (string)$imagesCollection[0]->getUrl();
            }

            $product->setImages(
                new \Magento\Framework\DataObject(
                    [
                        'collection'    => $imagesCollection,
                        'title'         => $product->getName(),
                        'thumbnail'     => $thumbnail,
                        'alt'           => $this->getCurrentProductImageAlt($product, $storeId),
                    ]
                )
            );
        }

        if ($this->isProductVideoEnabled && IncludeImage::INCLUDE_ALL == $imageIncludePolicy) {
            $videosCollection = $this->_getAllProductVideos($product, $storeId);

            if ($videosCollection) {
                $product->setVideos($videosCollection);
            }
        }
    }

    /**
     * @param \Magento\Catalog\Model\Product $product
     * @param int $storeId
     * @return array
     */
    protected function _getAllProductImages($product, $storeId)
    {
        $gallery = $this->getProductGallery($product, $storeId);

        $imagesCollection = [];
        if ($gallery) {
            foreach ($gallery as $image) {
                if (($image['media_type'] ?? null) === self::MEDIA_TYPE_VIDEO || !empty($image['disabled'])) {
                    continue;
                }

                $imagesCollection[] = new \Magento\Framework\DataObject(
                    [
                        'url'       => $this->getCurrentProductImageUrl($product, $image['file'], $storeId),
                        'caption'   => $image['label'] ? $image['label'] : $image['label_default'],
                    ]
                );
            }
        }

        return $imagesCollection;
    }

    /**
     * @param \Magento\Catalog\Model\Product $product
     * @param int $storeId
     * @return \Magento\Framework\DataObject[]
     */
    protected function _getAllProductVideos($product, $storeId)
    {
        $gallery = $this->getProductGallery($product, $storeId);

        $videosCollection = [];
        foreach ($gallery as $image) {
            if (($image['media_type'] ?? null) !== self::MEDIA_TYPE_VIDEO
                || empty($image['video_url'])
                || !empty($image['disabled'])
            ) {
                continue;
            }

            $videosCollection[] = new \Magento\Framework\DataObject(
                [
                    'player_loc'  => $image['video_url'],
                    'title'       => $image['video_title'] ?: $image['label'] ?: $image['label_default'] ?: $product->getName(),
                    'description' => $image['video_description'] ?: $product->getName(),
                    'thumbnail'   => $this->getCurrentProductImageUrl($product, $image['file'], $storeId),
                ]
            );
        }

        return $videosCollection;
    }

    /**
     * @param \Magento\Catalog\Model\Product $product
     * @param int $storeId
     * @return array
     */
    private function getProductGallery($product, $storeId): array
    {
        $cacheKey = $product->getId() . ':' . $storeId;

        if (!isset($this->productGalleryCache[$cacheKey])) {
            $product->setStoreId($storeId);

            $this->productGalleryCache[$cacheKey] = $this->mediaGalleryResourceModel->loadProductGalleryByAttributeId(
                $product,
                $this->mediaGalleryReadHandler->getAttribute()->getId()
            );
        }

        return $this->productGalleryCache[$cacheKey];
    }

    /**
     * @param \Magento\Catalog\Model\Product $product
     * @param mixed $image
     * @param int $storeId
     * @return string
     */
    protected function getCurrentProductImageUrl($product, $image, $storeId)
    {
        if ($this->isImageFriendlyUrlEnabled && $this->imageUrlTemplate && $this->productRepository !== null && $this->friendlyImageUrlService !== null) {
            $product = $this->productRepository->getById($product->getId(), false, $storeId);
            $image = $this->friendlyImageUrlService->getFriendlyImageName($product, $image);
        }

        if ($this->catalogImageHelper === null) {
            return (string)$image;
        }

        /** @var \Magento\Catalog\Model\Product $product */
        $imageHelper = $this->catalogImageHelper->init($product, 'product_page_image_large')
            ->setImageFile($image);

        return $imageHelper->getUrl();
    }

    /**
     * @param \Magento\Catalog\Model\Product $product
     * @param int $storeId
     *
     * @return string
     */
    protected function getCurrentProductImageAlt($product, $storeId)
    {
        if ($this->productRepository === null || $this->friendlyImageUrlService === null) {
            return '';
        }
        $product = $this->productRepository->getById($product->getId(), false, $storeId);

        return $this->friendlyImageUrlService->getFriendlyImageAlt($product, $storeId);
    }

    /**
     * @param mixed $imageUrlTemplate
     * @return bool
     */
    protected function isEnoughData($imageUrlTemplate)
    {
        $imageUrlTemplate = str_replace(
            [
                '[product_name]',
                '[product_sku]',
            ],
            '',
            $imageUrlTemplate
        );

        if (strpos($imageUrlTemplate, ']') !== false) {
            return false;
        }

        return true;
    }

    private function addStockFilter(StoreInterface $store): void
    {
        if ($this->sitemapConfig === null || $this->sitemapConfig->getIncludeOutOfStockProducts((int)$store->getId())) {
            return;
        }

        if ($this->isMsiEnabled()) {
            $stockIndexTable = $this->getTable('inventory_stock_1');
            if ($this->stockResolver) {
                try {
                    $website = $this->_storeManager->getWebsite($store->getWebsiteId());
                    $stock = $this->stockResolver->execute('website', (string)$website->getCode());
                    $stockId = $stock->getStockId();
                    $stockIndexTable = $this->getTable('inventory_stock_' . $stockId);
                } catch (\Exception $e) {
                    $stockIndexTable = $this->getTable('inventory_stock_1');
                }
            }

            $this->_select->joinInner(
                ['msi_stock' => $stockIndexTable],
                'e.sku = msi_stock.sku',
                []
            )->where('msi_stock.is_salable = ?', 1);
        } else {
            $stockStatusTable = $this->getTable('cataloginventory_stock_status');
            $this->_select->joinInner(
                ['stock' => $stockStatusTable],
                'e.entity_id = stock.product_id AND stock.website_id = 0',
                []
            )->where('stock.stock_status = ?', 1);
        }
    }

    private function validateStock(string $sku, StoreInterface $store): bool
    {
        if ($this->sitemapConfig === null || $this->sitemapConfig->getIncludeOutOfStockProducts((int)$store->getId())) {
            return true;
        }

        if (!$this->isMsiEnabled()) {
            return true;
        }

        if (!$this->getProductSalableQty || !$this->stockResolver) {
            return true;
        }

        try {
            $website = $this->_storeManager->getWebsite($store->getWebsiteId());
            $stock = $this->stockResolver->execute('website', (string)$website->getCode());
            $salableQty = $this->getProductSalableQty->execute($sku, (int)$stock->getStockId());
            return $salableQty > 0;
        } catch (\Exception $e) {
            return true;
        }
    }

    private function isMsiEnabled(): bool
    {
        return $this->moduleManager !== null &&
            $this->moduleManager->isEnabled('Magento_Inventory') &&
            $this->moduleManager->isEnabled('Magento_InventorySales');
    }
}
