<?php
/** @var \Mirasvit\Seo\Block\Adminhtml\System\Message\TrailingSlash $block */
?>

<div data-id="information-dialog-applytrailingslash-message" class="messages" hidden>
    <div class="message message-notice">
    	<div><?php /* @escapeNotVerified */ echo __('This operation can take a long time.'); ?></div>
    	<div><?php /* @escapeNotVerified */ echo __('All URLs will be changed. This action cannot be undone. Do you want to confirm it?'); ?></div>
    </div>
</div>
