<?php
/**
 * Mirasvit
 *
 * This source file is subject to the Mirasvit Software License, which is available at https://mirasvit.com/license/.
 * Do not edit or add to this file if you wish to upgrade the to newer versions in the future.
 * If you wish to customize this module for your needs.
 * Please refer to http://www.magentocommerce.com for more information.
 *
 * @category  Mirasvit
 * @package   mirasvit/module-seo
 * @version   2.12.8
 * @copyright Copyright (C) 2026 Mirasvit (https://mirasvit.com/)
 */



namespace Mirasvit\Seo\Ui\Redirect\Listing\Source;

use Magento\Framework\Data\OptionSourceInterface;

/**
 * Grid column / filter options for the redirect "Source" column:
 * 0 = Manual, 1 = Auto (auto-generated by product lifecycle).
 */
class Source implements OptionSourceInterface
{
    /**
     * @var array
     */
    protected $options;

    /**
     * @return array
     */
    public function toOptionArray()
    {
        if ($this->options !== null) {
            return $this->options;
        }

        $this->options = [
            ['value' => '0', 'label' => __('Manual')],
            ['value' => '1', 'label' => __('Auto')],
        ];

        return $this->options;
    }
}
