<?php
/**
 * Mirasvit
 *
 * This source file is subject to the Mirasvit Software License, which is available at https://mirasvit.com/license/.
 * Do not edit or add to this file if you wish to upgrade the to newer versions in the future.
 * If you wish to customize this module for your needs.
 * Please refer to http://www.magentocommerce.com for more information.
 *
 * @category  Mirasvit
 * @package   mirasvit/module-seo
 * @version   2.12.8
 * @copyright Copyright (C) 2026 Mirasvit (https://mirasvit.com/)
 */



namespace Mirasvit\Seo\Model;

use Magento\Framework\DataObject\IdentityInterface;
use Mirasvit\Seo\Api\Data\RedirectInterface;

class Redirect extends \Magento\Framework\Model\AbstractModel implements IdentityInterface, RedirectInterface
{
    const CACHE_TAG = 'seo_redirect';

    /**
     * @var string
     */
    protected $_cacheTag = 'seo_redirect';//@codingStandardsIgnoreLine
    /**
     * @var string
     */
    protected $_eventPrefix = 'seo_redirect';//@codingStandardsIgnoreLine

    /**
     * Get identities.
     *
     * @return array
     */
    public function getIdentities()
    {
        return [self::CACHE_TAG.'_'.$this->getId()];
    }

    /**
     * @return void
     */
    protected function _construct()
    {
        $this->_init('Mirasvit\Seo\Model\ResourceModel\Redirect');
    }

    /**
     * @return string|null
     */
    public function getUrlFrom(): ?string
    {
        return $this->getData(self::URL_FROM);
    }

    /**
     * @param string|null $value
     * @return RedirectInterface
     */
    public function setUrlFrom(?string $value): RedirectInterface
    {
        return $this->setData(self::URL_FROM, $value);
    }

    /**
     * @return string|null
     */
    public function getUrlTo(): ?string
    {
        return $this->getData(self::URL_TO);
    }

    /**
     * @param string|null $value
     * @return RedirectInterface
     */
    public function setUrlTo(?string $value): RedirectInterface
    {
        return $this->setData(self::URL_TO, $value);
    }

    /**
     * @return int|null
     */
    public function getIsRedirectOnlyErrorPage(): ?int
    {
        $value = $this->getData(self::IS_REDIRECT_ONLY_ERROR_PAGE);
        return $value !== null ? (int)$value : null;
    }

    /**
     * @param int|null $value
     * @return RedirectInterface
     */
    public function setIsRedirectOnlyErrorPage(?int $value): RedirectInterface
    {
        return $this->setData(self::IS_REDIRECT_ONLY_ERROR_PAGE, $value);
    }

    /**
     * @return string|null
     */
    public function getComments(): ?string
    {
        return $this->getData(self::COMMENTS);
    }

    /**
     * @param string|null $value
     * @return RedirectInterface
     */
    public function setComments(?string $value): RedirectInterface
    {
        return $this->setData(self::COMMENTS, $value);
    }

    /**
     * @return int|null
     */
    public function getIsActive(): ?int
    {
        $value = $this->getData(self::IS_ACTIVE);
        return $value !== null ? (int)$value : null;
    }

    /**
     * @param int|null $value
     * @return RedirectInterface
     */
    public function setIsActive(?int $value): RedirectInterface
    {
        return $this->setData(self::IS_ACTIVE, $value);
    }

    /**
     * @return int|null
     */
    public function getRedirectType(): ?int
    {
        $value = $this->getData(self::REDIRECT_TYPE);
        return $value !== null ? (int)$value : null;
    }

    /**
     * @param int|null $value
     * @return RedirectInterface
     */
    public function setRedirectType(?int $value): RedirectInterface
    {
        return $this->setData(self::REDIRECT_TYPE, $value);
    }

    /**
     * @return int|null
     */
    public function getIsAutogenerated(): ?int
    {
        $value = $this->getData(self::IS_AUTOGENERATED);

        return $value !== null ? (int)$value : null;
    }

    /**
     * @param int|null $value
     * @return RedirectInterface
     */
    public function setIsAutogenerated(?int $value): RedirectInterface
    {
        return $this->setData(self::IS_AUTOGENERATED, $value);
    }

    /**
     * @return int|null
     */
    public function getSourceProductId(): ?int
    {
        $value = $this->getData(self::SOURCE_PRODUCT_ID);

        return $value !== null ? (int)$value : null;
    }

    /**
     * @param int|null $value
     * @return RedirectInterface
     */
    public function setSourceProductId(?int $value): RedirectInterface
    {
        return $this->setData(self::SOURCE_PRODUCT_ID, $value);
    }

    public function getStoreIds(): array
    {
        return (array)$this->getData(self::STORE_IDS);
    }

    public function setStoreIds(array $value): RedirectInterface
    {
        return $this->setData(self::STORE_IDS, $value);
    }
}
